### ISSUE TITLE
How did you generate Apache Ignite with JHipster?

### ISSUE THREAD

**Issue by pavankjadda** [pierre-filliolaud/jhipster-ignite-app#1]
Hello,
I couldn't find a way to generate Apache Ignite with JHipster. How did you generate it? Please let me know the process.

**Comment by pierre-filliolaud** [comment]
Hi @pavankjadda ,

I've generated this project with hipster generator and modified it to integrate ignite.
Don't know if it still work.

Regards,
Pierre

**Comment by pavankjadda** [comment]
I understood that this morning. I went through your code file by file. I generated [new project](https://github.com/pavankjadda/ApacheIgnite-JHipster-Docker) using JHipster
